<a href="https://colab.research.google.com/github/tarannump096-cpu/Tensorflow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf


In [ ]:
a=tf.constant([4,5,6,7,8,9])

In [ ]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
import tensorflow as tf
a1=tf.constant(34)
a2=tf.constant(56)

In [ ]:
a1+a2

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [ ]:
tf.add(a1,a2)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [ ]:
tf.multiply(a1,a2)

<tf.Tensor: shape=(), dtype=int32, numpy=1904>

In [ ]:
m1=tf.constant([[2,3],[4,5]])
m2=tf.constant([[5,6],[7,8]])

In [ ]:
tf.matmul(m1,m2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 36],
       [55, 64]], dtype=int32)>

In [ ]:
aa=tf.constant([2.2,-3.0,-0.9,1])

In [ ]:
tf.nn.relu(aa)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 0. , 0. , 1. ], dtype=float32)>

In [ ]:
tf.nn.sigmoid(aa)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.90024954, 0.04742587, 0.2890505 , 0.7310586 ], dtype=float32)>

In [ ]:
tf.nn.tanh(aa)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.97574323, -0.9950547 , -0.71629786,  0.7615942 ], dtype=float32)>

In [ ]:
b1=tf.constant([[4,5,6,7,8]])
b2=tf.constant([[1,2,3,4,5]])

In [ ]:
b1*b2

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 4, 10, 18, 28, 40]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
c1=np.array([4,5,6,7,8])
c2=np.array([1,2,3,4,5])

In [ ]:
c1*c2

array([ 4, 10, 18, 28, 40])

In [ ]:
bb1=tf.constant([[2.5]])

In [ ]:
bb2=tf.constant([[1.2]])

In [ ]:
bb1*bb2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[3.]], dtype=float32)>

In [ ]:
bb3=tf.Variable([2.1])

In [ ]:
bb1*bb3

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[5.25]], dtype=float32)>

In [ ]:
tf.matmul(bb1,bb3)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [1,1] vs. [1] [Op:MatMul] name: 

In [ ]:
inputs=tf.Variable([[2.3]])
weight=tf.Variable([[1.2]])
bias=tf.Variable([[1.0]])

In [ ]:
w=inputs*weight+bias

In [ ]:
w=tf.matmul(inputs,weight)

In [ ]:
w

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.76]], dtype=float32)>

In [ ]:
res=w+bias

In [ ]:
tf.nn.relu(res)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[3.76]], dtype=float32)>

In [ ]:
inputs=tf.constant([[2.5]])
weights=tf.constant([[0.5,0.8,0.6]])
bias=tf.constant([[0.1]])
o11=tf.matmul(inputs,weights)+bias

In [ ]:
o11

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.35, 2.1 , 1.6 ]], dtype=float32)>

In [ ]:
import tensorflow as tf
inputs=tf.Variable([[2.3]])
weight=tf.Variable([[0.0, 0.1]])
bias=tf.Variable([[1.0]])
w=tf.matmul(inputs,weight)
res=w+bias
tf.nn.leaky_relu(res)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.  , 1.23]], dtype=float32)>